//
//  JournalEntry.swift
//  Journal
//
//  Created by Andy Dobbs on 1/5/24.
//

import Foundation
import SwiftData

@Model
final class JournalEntry {
    var title: String = ""
    var text: String = ""
    var rating: Double = 1.0
    var date: Date = Date()
    
    init(title: String, text: String, rating: Double, date: Date) {
        self.title = title
        self.text = text
        self.rating = rating
        self.date = date
    }
}

//let journalEntries: [JournalEntry] = [
//    JournalEntry(title: "New Year's Eve", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget.", rating: 4, date: Date()),
//    JournalEntry(title: "Ate a Burger", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget.", rating: 4, date: Date()),
//    JournalEntry(title: "Slept like an asthmatic", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget.", rating: 2, date: Date()),
//    JournalEntry(title: "Played Teamfight Tactics", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Enim nunc faucibus a pellentesque. Mauris cursus mattis molestie a. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Et malesuada fames ac turpis egestas sed tempus urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Amet mauris commodo quis imperdiet massa. Ullamcorper morbi tincidunt ornare massa eget.", rating: 5, date: Date()),
//]
